In [2]:
import numpy as np

## Creating Arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
np.array([1, 4, 7,7, 9, 79, 12])

array([ 1,  4,  7,  7,  9, 79, 12])

In [7]:
a = np.array([1, 4, 7,7, 9, 79, 12])
a

array([ 1,  4,  7,  7,  9, 79, 12])

In [8]:
# access elemet 3
a[2]

np.int64(7)

In [10]:
# change an element 
a[2] = 10
a

array([ 1,  4, 10,  7,  9, 79, 12])

In [ ]:
np.arange(10) #array from 0 to 10 exclusive

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3, 10) #array from 3 to 10 exclusive

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 100, 11) #create 11 numbers between 0 and 100 inclusive

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional Array

In [ ]:
np.zeros((5, 2)) # row by column

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.array (
    [[1,2,3],
    [4,5,6],
    [7, 8, 9]]
) #convert list to array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
n = np.array (
    [[1,2,3],
    [4,5,6],
    [7, 8, 9]]
)

In [21]:
n[0][1] # access element at row 0 and column 1

np.int64(2)

In [ ]:
n[0, 1] = 20 #change elemt at row 0 and col 1
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
n[2] #access third row

array([7, 8, 9])

In [25]:
n[2] = [1, 1, 1] # change the whole row
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
# get entire second col
n[:, 1]

array([20,  5,  1])

## Randomly Generate Arrays

In [ ]:
np.random.rand(5, 5) #uniform distribution over [0, 1]

array([[0.12619324, 0.68957097, 0.3957345 , 0.54974594, 0.03437809],
       [0.55981624, 0.06409977, 0.88382923, 0.33573248, 0.13272962],
       [0.61451441, 0.25833898, 0.15183816, 0.11170236, 0.02985958],
       [0.70111479, 0.8888029 , 0.3453119 , 0.99326525, 0.36595822],
       [0.16435409, 0.52776662, 0.75032328, 0.34461746, 0.02149585]])

In [ ]:
# make results reproducible, u
np.random.seed(4)
np.random.rand(5,5)

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599, 0.69772882],
       [0.2160895 , 0.97627445, 0.00623026, 0.25298236, 0.43479153],
       [0.77938292, 0.19768507, 0.86299324, 0.98340068, 0.16384224],
       [0.59733394, 0.0089861 , 0.38657128, 0.04416006, 0.95665297],
       [0.43614665, 0.94897731, 0.78630599, 0.8662893 , 0.17316542]])

In [ ]:
# make results reproducible (normal dist)
np.random.seed(4)
np.random.randn(5,5)

array([[ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152],
       [-1.58457724, -0.64770677,  0.59857517,  0.33225003, -1.14747663],
       [ 0.61866969, -0.08798693,  0.4250724 ,  0.33225315, -1.15681626],
       [ 0.35099715, -0.60688728,  1.54697933,  0.72334161,  0.04613557],
       [-0.98299165,  0.05443274,  0.15989294, -1.20894816,  2.22336022]])

In [34]:
# make results reproducible and specify size
np.random.seed(4)
np.random.randint(low = 0, high = 10, size=(5,5))

array([[7, 5, 1, 8, 7],
       [8, 2, 9, 7, 7],
       [7, 9, 8, 4, 2],
       [6, 4, 3, 0, 7],
       [5, 5, 9, 6, 6]])

In [37]:
# specify mean (3) and std (2.5)
# make results reproducible
3 + 2.5 * np.random.randn(2, 5)

array([[ 3.42379438,  1.21193631,  4.3133347 ,  1.13153081,  4.8745476 ],
       [-3.14953701,  3.09000923,  4.81532359,  6.5831934 ,  9.63699851]])

## Element-wise Operation

In [40]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b = a + 1 #add 1 to all elements of the array
b

array([1, 2, 3, 4, 5])

In [45]:
c = (10 + (a *2))**2
c

array([100, 144, 196, 256, 324])

In [46]:
a + c

array([100, 145, 198, 259, 328])

## Comparison Operations

In [48]:
a

array([0, 1, 2, 3, 4])

In [47]:
a >= 2

array([False, False,  True,  True,  True])

In [49]:
a > b

array([False, False, False, False, False])

In [52]:
a[a>=2] # returns all elements of array a that are >= 2, i.e satisfy the condition

array([2, 3, 4])

## Summary Operations

In [54]:
a

array([0, 1, 2, 3, 4])

In [55]:
a.mean()

np.float64(2.0)

In [56]:
a.std()

np.float64(1.4142135623730951)

In [57]:
b.min()

np.int64(1)

In [58]:
b.max()

np.int64(5)